import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `vitest --coverage` (vitest.config.ts) — linting it makes
    // a local `npm run lint` after a coverage run disagree with CI, which
    // never generates this directory.
    "coverage/**",
    // packages/* are standalone npm packages with their own dependencies,
    // installed separately from the app's. Linting them from here resolves
    // imports against the wrong node_modules.
    "packages/**",
  ]),
]);

export default eslintConfig;
